/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MONGODB_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PORT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PaisaApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "PaisaService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "PaisaVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}